theme: Minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate-v2
  - jemoji
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-optional-front-matter
  - jekyll-assets